export const forexSymbols = [
  {
    symbol: 'OANDA:EUR_USD',
    displayName: 'EUR/USD'
  },
  {
    symbol: 'OANDA:GBP_USD',
    displayName: 'GBP/USD'
  },
  {
    symbol: 'OANDA:NAS100_USD',
    displayName: 'NASDAQ 100'
  },
  {
    symbol: 'OANDA:SUGAR_USD',
    displayName: 'Sugar'
  },
  {
    symbol: 'OANDA:XCU_USD',
    displayName: 'Copper'
  },
  {
    symbol: 'OANDA:SOYBN_USD',
    displayName: 'Soybeans'
  },
  {
    symbol: 'OANDA:USB30Y_USD',
    displayName: 'US 30-Year T-Bond'
  },
  {
    symbol: 'OANDA:US30_USD',
    displayName: 'US 30'
  },
  {
    symbol: 'OANDA:NATGAS_USD',
    displayName: 'Natural Gas'
  },
  {
    symbol: 'OANDA:WHEAT_USD',
    displayName: 'Wheat'
  },
  {
    symbol: 'OANDA:US2000_USD',
    displayName: 'US 2000'
  },
  {
    symbol: 'OANDA:BCO_USD',
    displayName: 'Brent Crude Oil'
  },
  {
    symbol: 'OANDA:XPT_USD',
    displayName: 'Platinum'
  },
  {
    symbol: 'OANDA:JP225_USD',
    displayName: 'Japan 225'
  },
  {
    symbol: 'OANDA:WTICO_USD',
    displayName: 'WTI Crude Oil'
  },
  {
    symbol: 'OANDA:XAG_USD',
    displayName: 'Silver'
  },
  {
    symbol: 'OANDA:USB02Y_USD',
    displayName: 'US 2-Year T-Note'
  },
  {
    symbol: 'OANDA:AUD_USD',
    displayName: 'AUD/USD'
  },
  {
    symbol: 'OANDA:XPD_USD',
    displayName: 'Palladium'
  },
  {
    symbol: 'OANDA:USB05Y_USD',
    displayName: 'US 5-Year T-Note'
  },
  {
    symbol: 'OANDA:XAU_USD',
    displayName: 'Gold'
  },
  {
    symbol: 'OANDA:SPX500_USD',
    displayName: 'S&P 500'
  },
  {
    symbol: 'OANDA:CORN_USD',
    displayName: 'Corn'
  },
  {
    symbol: 'OANDA:USB10Y_USD',
    displayName: 'US 10-Year T-Note'
  },
  {
    symbol: 'OANDA:CN50_USD',
    displayName: 'China 50'
  },
  {
    symbol: 'OANDA:NZD_USD',
    displayName: 'NZD/USD'
  }
]
export const favSymbols = [
  {
    symbol: 'OANDA:EUR_USD',
    displayName: 'EUR/USD'
  },
  {
    symbol: 'OANDA:GBP_USD',
    displayName: 'GBP/USD'
  },
  {
    symbol: 'AAPL',
    displayName: 'Apple'
  },
  {
    symbol: 'MSFT',
    displayName: 'Microsoft'
  },
  {
    symbol: 'META',
    displayName: 'META'
  },
  {
    symbol: 'OANDA:XAU_USD',
    displayName: 'Gold'
  }
]

export const symbolsName = {
  AAPL: 'Apple',
  'BINANCE:BTCUSDT': 'BTCUSDT',
  MSFT: 'Microsoft',
  META: 'META',
  'OANDA:EUR_USD': 'EUR/USD',
  'OANDA:GBP_USD': 'GBP/USD',
  'OANDA:NAS100_USD': 'NASDAQ 100',
  'OANDA:SUGAR_USD': 'Sugar',
  'OANDA:XCU_USD': 'Copper',
  'OANDA:SOYBN_USD': 'Soybeans',
  'OANDA:USB30Y_USD': 'US 30-Year T-Bond',
  'OANDA:US30_USD': 'US 30',
  'OANDA:NATGAS_USD': 'Natural Gas',
  'OANDA:WHEAT_USD': 'Wheat',
  'OANDA:US2000_USD': 'US 2000',
  'OANDA:BCO_USD': 'Brent Crude Oil',
  'OANDA:XPT_USD': 'Platinum',
  'OANDA:JP225_USD': 'Japan 225',
  'OANDA:WTICO_USD': 'WTI Crude Oil',
  'OANDA:XAG_USD': 'Silver',
  'OANDA:USB02Y_USD': 'US 2-Year T-Note',
  'OANDA:AUD_USD': 'AUD/USD',
  'OANDA:XPD_USD': 'Palladium',
  'OANDA:USB05Y_USD': 'US 5-Year T-Note',
  'OANDA:XAU_USD': 'Gold',
  'OANDA:SPX500_USD': 'S&P 500',
  'OANDA:CORN_USD': 'Corn',
  'OANDA:USB10Y_USD': 'US 10-Year T-Note',
  'OANDA:CN50_USD': 'China 50',
  'OANDA:NZD_USD': 'NZD/USD'
}

export const cryptoSymbols = [
  { symbol: 'BINANCE:TWTBUSD', displayName: 'TWT/BUSD' },
  { symbol: 'BINANCE:BNBBUSD', displayName: 'BNB/BUSD' },
  { symbol: 'BINANCE:AIONBUSD', displayName: 'AION/BUSD' },
  { symbol: 'BINANCE:XECBUSD', displayName: 'XEC/BUSD' },
  { symbol: 'BINANCE:ZECTUSD', displayName: 'ZEC/TUSD' },
  { symbol: 'BINANCE:STMXBUSD', displayName: 'STMX/BUSD' },
  { symbol: 'BINANCE:NEARBUSD', displayName: 'NEAR/BUSD' },
  { symbol: 'BINANCE:RUNEBUSD', displayName: 'RUNE/BUSD' },
  { symbol: 'BINANCE:FTMFDUSD', displayName: 'FTM/FDUSD' },
  { symbol: 'BINANCE:EPSBUSD', displayName: 'EPS/BUSD' },
  { symbol: 'BINANCE:KSMBUSD', displayName: 'KSM/BUSD' },
  { symbol: 'BINANCE:TKOBUSD', displayName: 'TKO/BUSD' },
  { symbol: 'BINANCE:NEBLBUSD', displayName: 'NEBL/BUSD' },
  { symbol: 'BINANCE:TORNBUSD', displayName: 'TORN/BUSD' },
  { symbol: 'BINANCE:WOOBUSD', displayName: 'WOO/BUSD' },
  { symbol: 'BINANCE:SWRVBUSD', displayName: 'SWRV/BUSD' },
  { symbol: 'BINANCE:RPLBUSD', displayName: 'RPL/BUSD' },
  { symbol: 'BINANCE:CREAMBUSD', displayName: 'CREAM/BUSD' },
  { symbol: 'BINANCE:LEVERBUSD', displayName: 'LEVER/BUSD' },
  { symbol: 'BINANCE:NEOTUSD', displayName: 'NEO/TUSD' },
  { symbol: 'BINANCE:GTOTUSD', displayName: 'GTO/TUSD' },
  { symbol: 'BINANCE:LINKTUSD', displayName: 'LINK/TUSD' },
  { symbol: 'BINANCE:BTTBUSD', displayName: 'BTT/BUSD' },
  { symbol: 'BINANCE:KLAYBUSD', displayName: 'KLAY/BUSD' },
  { symbol: 'BINANCE:TRBBUSD', displayName: 'TRB/BUSD' },
  { symbol: 'BINANCE:PENDLETUSD', displayName: 'PENDLE/TUSD' },
  { symbol: 'BINANCE:MBOXBUSD', displayName: 'MBOX/BUSD' },
  { symbol: 'BINANCE:BICOBUSD', displayName: 'BICO/BUSD' },
  { symbol: 'BINANCE:FTTBUSD', displayName: 'FTT/BUSD' },
  { symbol: 'BINANCE:DNTBUSD', displayName: 'DNT/BUSD' },
  { symbol: 'BINANCE:ATOMTUSD', displayName: 'ATOM/TUSD' },
  { symbol: 'BINANCE:BSWBUSD', displayName: 'BSW/BUSD' },
  { symbol: 'BINANCE:EDUTUSD', displayName: 'EDU/TUSD' },
  { symbol: 'BINANCE:BLZFDUSD', displayName: 'BLZ/FDUSD' },
  { symbol: 'BINANCE:SCRTBUSD', displayName: 'SCRT/BUSD' },
  { symbol: 'BINANCE:SYSBUSD', displayName: 'SYS/BUSD' },
  { symbol: 'BINANCE:BTCSTBUSD', displayName: 'BTCST/BUSD' },
  { symbol: 'BINANCE:MBLBUSD', displayName: 'MBL/BUSD' },
  { symbol: 'BINANCE:ADAFDUSD', displayName: 'ADA/FDUSD' },
  { symbol: 'BINANCE:HFTBUSD', displayName: 'HFT/BUSD' },
  { symbol: 'BINANCE:RAREBUSD', displayName: 'RARE/BUSD' },
  { symbol: 'BINANCE:FTMBUSD', displayName: 'FTM/BUSD' },
  { symbol: 'BINANCE:ALCXBUSD', displayName: 'ALCX/BUSD' },
  { symbol: 'BINANCE:LDOFDUSD', displayName: 'LDO/FDUSD' },
  { symbol: 'BINANCE:NANOBUSD', displayName: 'NANO/BUSD' },
  { symbol: 'BINANCE:VITEBUSD', displayName: 'VITE/BUSD' },
  { symbol: 'BINANCE:ETHFDUSD', displayName: 'ETH/FDUSD' },
  { symbol: 'BINANCE:LSKBUSD', displayName: 'LSK/BUSD' },
  { symbol: 'BINANCE:ANYBUSD', displayName: 'ANY/BUSD' },
  { symbol: 'BINANCE:BAKEBUSD', displayName: 'BAKE/BUSD' },
  { symbol: 'BINANCE:SCBUSD', displayName: 'SC/BUSD' },
  { symbol: 'BINANCE:SNMBUSD', displayName: 'SNM/BUSD' },
  { symbol: 'BINANCE:APTBUSD', displayName: 'APT/BUSD' },
  { symbol: 'BINANCE:IQBUSD', displayName: 'IQ/BUSD' },
  { symbol: 'BINANCE:1INCHBUSD', displayName: '1INCH/BUSD' },
  { symbol: 'BINANCE:INJFDUSD', displayName: 'INJ/FDUSD' },
  { symbol: 'BINANCE:MAGICBUSD', displayName: 'MAGIC/BUSD' },
  { symbol: 'BINANCE:BCPTTUSD', displayName: 'BCPT/TUSD' },
  { symbol: 'BINANCE:NFPTUSD', displayName: 'NFP/TUSD' },
  { symbol: 'BINANCE:YGGBUSD', displayName: 'YGG/BUSD' },
  { symbol: 'BINANCE:ATABUSD', displayName: 'ATA/BUSD' },
  { symbol: 'BINANCE:RAYBUSD', displayName: 'RAY/BUSD' },
  { symbol: 'BINANCE:MATICFDUSD', displayName: 'MATIC/FDUSD' },
  { symbol: 'BINANCE:MULTIBUSD', displayName: 'MULTI/BUSD' },
  { symbol: 'BINANCE:MLNBUSD', displayName: 'MLN/BUSD' },
  { symbol: 'BINANCE:FIROBUSD', displayName: 'FIRO/BUSD' },
  { symbol: 'BINANCE:ORDIFDUSD', displayName: 'ORDI/FDUSD' },
  { symbol: 'BINANCE:ALGOFDUSD', displayName: 'ALGO/FDUSD' },
  { symbol: 'BINANCE:ORNBUSD', displayName: 'ORN/BUSD' },
  { symbol: 'BINANCE:AAVEBUSD', displayName: 'AAVE/BUSD' },
  { symbol: 'BINANCE:TBUSD', displayName: 'TBUSD' },
  { symbol: 'BINANCE:XRPFDUSD', displayName: 'XRP/FDUSD' },
  { symbol: 'BINANCE:KMDBUSD', displayName: 'KMD/BUSD' },
  { symbol: 'BINANCE:IOTABUSD', displayName: 'IOTA/BUSD' },
  { symbol: 'BINANCE:BKRWBUSD', displayName: 'BKRW/BUSD' },
  { symbol: 'BINANCE:STRAXBUSD', displayName: 'STRAX/BUSD' },
  { symbol: 'BINANCE:PSGBUSD', displayName: 'PSG/BUSD' },
  { symbol: 'BINANCE:GLMRBUSD', displayName: 'GLMR/BUSD' },
  { symbol: 'BINANCE:WNXMBUSD', displayName: 'WNXM/BUSD' },
  { symbol: 'BINANCE:TFUELTUSD', displayName: 'TFUEL/TUSD' },
  { symbol: 'BINANCE:PORTOBUSD', displayName: 'PORTO/BUSD' },
  { symbol: 'BINANCE:OOKIBUSD', displayName: 'OOKI/BUSD' },
  { symbol: 'BINANCE:AVAXFDUSD', displayName: 'AVAX/FDUSD' },
  { symbol: 'BINANCE:BCHTUSD', displayName: 'BCH/TUSD' },
  { symbol: 'BINANCE:GALABUSD', displayName: 'GALA/BUSD' },
  { symbol: 'BINANCE:ZILBUSD', displayName: 'ZIL/BUSD' },
  { symbol: 'BINANCE:HBARBUSD', displayName: 'HBAR/BUSD' },
  { symbol: 'BINANCE:AIFDUSD', displayName: 'AIFD/USD' },
  { symbol: 'BINANCE:SANDFDUSD', displayName: 'SAND/FDUSD' },
  { symbol: 'BINANCE:RENBUSD', displayName: 'REN/BUSD' },
  { symbol: 'BINANCE:STEEMBUSD', displayName: 'STEEM/BUSD' },
  { symbol: 'BINANCE:CTXCBUSD', displayName: 'CTXC/BUSD' },
  { symbol: 'BINANCE:DAIBUSD', displayName: 'DAI/BUSD' },
  { symbol: 'BINANCE:LTCTUSD', displayName: 'LTC/TUSD' },
  { symbol: 'BINANCE:FLMBUSD', displayName: 'FLM/BUSD' },
  { symbol: 'BINANCE:TRXTUSD', displayName: 'TRX/TUSD' },
  { symbol: 'BINANCE:DUSKBUSD', displayName: 'DUSK/BUSD' },
  { symbol: 'BINANCE:BCHABCBUSD', displayName: 'BCHABC/BUSD' },
  { symbol: 'BINANCE:XRPBUSD', displayName: 'XRP/BUSD' },
  { symbol: 'BINANCE:AUTOBUSD', displayName: 'AUTO/BUSD' },
  { symbol: 'BINANCE:LPTBUSD', displayName: 'LPT/BUSD' },
  { symbol: 'BINANCE:EURBUSD', displayName: 'EUR/BUSD' },
  { symbol: 'BINANCE:USDCTUSD', displayName: 'USDC/TUSD' },
  { symbol: 'BINANCE:SXPBUSD', displayName: 'SXP/BUSD' },
  { symbol: 'BINANCE:ONETUSD', displayName: 'ONE/TUSD' },
  { symbol: 'BINANCE:KAVABUSD', displayName: 'KAVA/BUSD' },
  { symbol: 'BINANCE:TLMBUSD', displayName: 'TLM/BUSD' },
  { symbol: 'BINANCE:DATABUSD', displayName: 'DATA/BUSD' },
  { symbol: 'BINANCE:ZRXBUSD', displayName: 'ZRX/BUSD' },
  { symbol: 'BINANCE:GTOBUSD', displayName: 'GTO/BUSD' },
  { symbol: 'BINANCE:ACABUSD', displayName: 'ACA/BUSD' },
  { symbol: 'BINANCE:POWRBUSD', displayName: 'POWR/BUSD' },
  { symbol: 'BINANCE:UTKBUSD', displayName: 'UTK/BUSD' },
  { symbol: 'BINANCE:ROSEBUSD', displayName: 'ROSE/BUSD' },
  { symbol: 'BINANCE:SUPERFDUSD', displayName: 'SUPER/FDUSD' },
  { symbol: 'BINANCE:LDOBUSD', displayName: 'LDO/BUSD' },
  { symbol: 'BINANCE:CELRBUSD', displayName: 'CELR/BUSD' },
  { symbol: 'BINANCE:CVPBUSD', displayName: 'CVP/BUSD' },
  { symbol: 'BINANCE:EOSBEARBUSD', displayName: 'EOSBEAR/BUSD' },
  { symbol: 'BINANCE:PONDBUSD', displayName: 'POND/BUSD' },
  { symbol: 'BINANCE:XNOBUSD', displayName: 'XNO/BUSD' },
  { symbol: 'BINANCE:SNTBUSD', displayName: 'SNT/BUSD' },
  { symbol: 'BINANCE:BNBTUSD', displayName: 'BNB/TUSD' },
  { symbol: 'BINANCE:ZENBUSD', displayName: 'ZEN/BUSD' },
  { symbol: 'BINANCE:DREPBUSD', displayName: 'DREP/BUSD' },
  { symbol: 'BINANCE:NUBUSD', displayName: 'NU/BUSD' },
  { symbol: 'BINANCE:BNBBULLBUSD', displayName: 'BNBBULL/BUSD' },
  { symbol: 'BINANCE:FILBUSD', displayName: 'FIL/BUSD' },
  { symbol: 'BINANCE:CLVBUSD', displayName: 'CLV/BUSD' },
  { symbol: 'BINANCE:GTCBUSD', displayName: 'GTC/BUSD' },
  { symbol: 'BINANCE:AMPBUSD', displayName: 'AMP/BUSD' },
  { symbol: 'BINANCE:STORJBUSD', displayName: 'STORJ/BUSD' },
  { symbol: 'BINANCE:XRPBEARBUSD', displayName: 'XRPBEAR/BUSD' },
  { symbol: 'BINANCE:ENSBUSD', displayName: 'ENS/BUSD' },
  { symbol: 'BINANCE:AMBBUSD', displayName: 'AMB/BUSD' },
  { symbol: 'BINANCE:NEXOBUSD', displayName: 'NEXO/BUSD' },
  { symbol: 'BINANCE:ACEFDUSD', displayName: 'ACE/FDUSD' },
  { symbol: 'BINANCE:1000SATSFDUSD', displayName: '1000SATS/FDUSD' },
  { symbol: 'BINANCE:QUICKBUSD', displayName: 'QUICK/BUSD' },
  { symbol: 'BINANCE:LDOTUSD', displayName: 'LDOT/USD' },
  { symbol: 'BINANCE:USDCBUSD', displayName: 'USDC/BUSD' },
  { symbol: 'BINANCE:AGIXBUSD', displayName: 'AGIX/BUSD' },
  { symbol: 'BINANCE:USTBUSD', displayName: 'UST/BUSD' },
  { symbol: 'BINANCE:ILVBUSD', displayName: 'ILV/BUSD' },
  { symbol: 'BINANCE:HIGHBUSD', displayName: 'HIGH/BUSD' },
  { symbol: 'BINANCE:ZECBUSD', displayName: 'ZEC/BUSD' },
  { symbol: 'BINANCE:ETHTUSD', displayName: 'ETH/TUSD' },
  { symbol: 'BINANCE:CYBERFDUSD', displayName: 'CYBER/FDUSD' },
  { symbol: 'BINANCE:OSMOBUSD', displayName: 'OSMO/BUSD' },
  { symbol: 'BINANCE:BURGERBUSD', displayName: 'BURGER/BUSD' },
  { symbol: 'BINANCE:WINBUSD', displayName: 'WIN/BUSD' },
  { symbol: 'BINANCE:DEXEBUSD', displayName: 'DEXE/BUSD' },
  { symbol: 'BINANCE:SHIBTUSD', displayName: 'SHIB/TUSD' },
  { symbol: 'BINANCE:SUPERBUSD', displayName: 'SUPER/BUSD' },
  { symbol: 'BINANCE:BTCBUSD', displayName: 'BTC/BUSD' },
  { symbol: 'BINANCE:WRXBUSD', displayName: 'WRX/BUSD' },
  { symbol: 'BINANCE:EPXBUSD', displayName: 'EPX/BUSD' },
  { symbol: 'BINANCE:OXTBUSD', displayName: 'OXT/BUSD' },
  { symbol: 'BINANCE:ATOMFDUSD', displayName: 'ATOM/FDUSD' },
  { symbol: 'BINANCE:POLYBUSD', displayName: 'POLY/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:PUNDIXBUSD', displayName: 'PUNDIX/BUSD' },
  { symbol: 'BINANCE:XMRBUSD', displayName: 'XMR/BUSD' },
  { symbol: 'BINANCE:USTCBUSD', displayName: 'USTC/BUSD' },
  { symbol: 'BINANCE:IOSTBUSD', displayName: 'IOST/BUSD' },
  { symbol: 'BINANCE:MEMEFDUSD', displayName: 'MEME/FDUSD' },
  { symbol: 'BINANCE:BADGERBUSD', displayName: 'BADGER/BUSD' },
  { symbol: 'BINANCE:PROSBUSD', displayName: 'PROS/BUSD' },
  { symbol: 'BINANCE:PLABUSD', displayName: 'PLA/BUSD' },
  { symbol: 'BINANCE:GNOBUSD', displayName: 'GNO/BUSD' },
  { symbol: 'BINANCE:VOXELBUSD', displayName: 'VOXEL/BUSD' },
  { symbol: 'BINANCE:JOEBUSD', displayName: 'JOE/BUSD' },
  { symbol: 'BINANCE:OPBUSD', displayName: 'OP/BUSD' },
  { symbol: 'BINANCE:ONEBUSD', displayName: 'ONE/BUSD' },
  { symbol: 'BINANCE:RLCBUSD', displayName: 'RLC/BUSD' },
  { symbol: 'BINANCE:RGTBUSD', displayName: 'RGT/BUSD' },
  { symbol: 'BINANCE:LRCBUSD', displayName: 'LRC/BUSD' },
  { symbol: 'BINANCE:SANDBUSD', displayName: 'SAND/BUSD' },
  { symbol: 'BINANCE:ALGOTUSD', displayName: 'ALGO/TUSD' },
  { symbol: 'BINANCE:RADBUSD', displayName: 'RAD/BUSD' },
  { symbol: 'BINANCE:STXBUSD', displayName: 'STX/BUSD' },
  { symbol: 'BINANCE:BETHBUSD', displayName: 'BETH/BUSD' },
  { symbol: 'BINANCE:CKBBUSD', displayName: 'CKB/BUSD' },
  { symbol: 'BINANCE:BNTBUSD', displayName: 'BNT/BUSD' },
  { symbol: 'BINANCE:SPELLBUSD', displayName: 'SPELL/BUSD' },
  { symbol: 'BINANCE:COMPTUSD', displayName: 'COMP/TUSD' },
  { symbol: 'BINANCE:BCHABUSD', displayName: 'BCHAB/BUSD' },
  { symbol: 'BINANCE:BTCTUSD', displayName: 'BTC/TUSD' },
  { symbol: 'BINANCE:SOLBUSD', displayName: 'SOL/BUSD' },
  { symbol: 'BINANCE:SSVBUSD', displayName: 'SSV/BUSD' },
  { symbol: 'BINANCE:SOLFDUSD', displayName: 'SOL/FDUSD' },
  { symbol: 'BINANCE:LOOMBUSD', displayName: 'LOOM/BUSD' },
  { symbol: 'BINANCE:RSRBUSD', displayName: 'RSR/BUSD' },
  { symbol: 'BINANCE:HEGICBUSD', displayName: 'HEGIC/BUSD' },
  { symbol: 'BINANCE:DOTFDUSD', displayName: 'DOT/FDUSD' },
  { symbol: 'BINANCE:LOKABUSD', displayName: 'LOKA/BUSD' },
  { symbol: 'BINANCE:BTTTUSD', displayName: 'BTT/TUSD' },
  { symbol: 'BINANCE:CYBERTUSD', displayName: 'CYBER/TUSD' },
  { symbol: 'BINANCE:FIROFDUSD', displayName: 'FIRO/FDUSD' },
  { symbol: 'BINANCE:BTCBEARBUSD', displayName: 'BTCBEAR/BUSD' },
  { symbol: 'BINANCE:FLOGBUSD', displayName: 'FLOG/BUSD' },
  { symbol: 'BINANCE:BANDBUSD', displayName: 'BAND/BUSD' },
  { symbol: 'BINANCE:AXSBUSD', displayName: 'AXS/BUSD' },
  { symbol: 'BINANCE:RLUSBUSD', displayName: 'RLU/BUSD' },
  { symbol: 'BINANCE:LUNABUSD', displayName: 'LUNA/BUSD' },
  { symbol: 'BINANCE:FTTFDUSD', displayName: 'FTT/FDUSD' },
  { symbol: 'BINANCE:ACRYPTOSBUSD', displayName: 'ACRYPTOS/BUSD' },
  { symbol: 'BINANCE:WINGBUSD', displayName: 'WING/BUSD' },
  { symbol: 'BINANCE:STARBUSD', displayName: 'STAR/BUSD' },
  { symbol: 'BINANCE:WTCBUSD', displayName: 'WTC/BUSD' },
  { symbol: 'BINANCE:STPTBUSD', displayName: 'STPT/BUSD' },
  { symbol: 'BINANCE:USDSBUSDT', displayName: 'USDS/BUSD' },
  { symbol: 'BINANCE:ERDBUSD', displayName: 'ERD/BUSD' },
  { symbol: 'BINANCE:ONTBUSD', displayName: 'ONT/BUSD' },
  { symbol: 'BINANCE:MDXBUSD', displayName: 'MDX/BUSD' },
  { symbol: 'BINANCE:ALGOBUSD', displayName: 'ALGO/BUSD' },
  { symbol: 'BINANCE:OAXBUSD', displayName: 'OAX/BUSD' },
  { symbol: 'BINANCE:ELABUSD', displayName: 'ELA/BUSD' },
  { symbol: 'BINANCE:ADXFDUSD', displayName: 'ADX/FDUSD' },
  { symbol: 'BINANCE:STPTTUSD', displayName: 'STPT/TUSD' },
  { symbol: 'BINANCE:RIFBUSD', displayName: 'RIF/BUSD' },
  { symbol: 'BINANCE:BTTBUSD', displayName: 'BTT/BUSD' },
  { symbol: 'BINANCE:BQXFDUSD', displayName: 'BQX/FDUSD' },
  { symbol: 'BINANCE:ETHBUSD', displayName: 'ETH/BUSD' },
  { symbol: 'BINANCE:SALTBUSD', displayName: 'SALT/BUSD' },
  { symbol: 'BINANCE:BTTUSDT', displayName: 'BTT/USDT' },
  { symbol: 'BINANCE:ICXBUSD', displayName: 'ICX/BUSD' },
  { symbol: 'BINANCE:TRXFDUSD', displayName: 'TRX/FDUSD' },
  { symbol: 'BINANCE:BQTBUSD', displayName: 'BQT/BUSD' },
  { symbol: 'BINANCE:VITEBUSD', displayName: 'VITE/BUSD' },
  { symbol: 'BINANCE:MODBUSD', displayName: 'MOD/BUSD' },
  { symbol: 'BINANCE:FTTBUSD', displayName: 'FTT/BUSD' },
  { symbol: 'BINANCE:FOAMBUSD', displayName: 'FOAM/BUSD' },
  { symbol: 'BINANCE:ATOMBUSD', displayName: 'ATOM/BUSD' },
  { symbol: 'BINANCE:FUNBUSD', displayName: 'FUN/BUSD' },
  { symbol: 'BINANCE:EVXFDUSD', displayName: 'EVX/FDUSD' },
  { symbol: 'BINANCE:LRCFDUSD', displayName: 'LRC/FDUSD' },
  { symbol: 'BINANCE:MBLBUSD', displayName: 'MBL/BUSD' },
  { symbol: 'BINANCE:FUNTUSD', displayName: 'FUN/TUSD' },
  { symbol: 'BINANCE:INJFDUSD', displayName: 'INJ/FDUSD' },
  { symbol: 'BINANCE:VIABUSD', displayName: 'VIA/BUSD' },
  { symbol: 'BINANCE:BTCBBTCBUSD', displayName: 'BTCBBTC/BUSD' },
  { symbol: 'BINANCE:XEMBUSD', displayName: 'XEM/BUSD' },
  { symbol: 'BINANCE:SHRTBUSD', displayName: 'SHRT/BUSD' },
  { symbol: 'BINANCE:NPXSBUSD', displayName: 'NPXS/BUSD' },
  { symbol: 'BINANCE:SNMBUSD', displayName: 'SNM/BUSD' },
  { symbol: 'BINANCE:REPUSDT', displayName: 'REP/USDT' },
  { symbol: 'BINANCE:DATABUSD', displayName: 'DATA/BUSD' },
  { symbol: 'BINANCE:GVTBUSD', displayName: 'GVT/BUSD' },
  { symbol: 'BINANCE:MTHBUSD', displayName: 'MTH/BUSD' },
  { symbol: 'BINANCE:XRPBUSD', displayName: 'XRP/BUSD' },
  { symbol: 'BINANCE:SALVABUSD', displayName: 'SALVA/BUSD' },
  { symbol: 'BINANCE:STMXBUSD', displayName: 'STMX/BUSD' },
  { symbol: 'BINANCE:TRXUSDT', displayName: 'TRX/USDT' },
  { symbol: 'BINANCE:KAVABUSD', displayName: 'KAVA/BUSD' },
  { symbol: 'BINANCE:ROSEBUSD', displayName: 'ROSE/BUSD' },
  { symbol: 'BINANCE:ZRXBUSD', displayName: 'ZRX/BUSD' },
  { symbol: 'BINANCE:MDTBUSD', displayName: 'MDT/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:MDXUSDT', displayName: 'MDX/USDT' },
  { symbol: 'BINANCE:BANDUSDT', displayName: 'BAND/USDT' },
  { symbol: 'BINANCE:PNKBUSD', displayName: 'PNK/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:DMTBUSD', displayName: 'DMT/BUSD' },
  { symbol: 'BINANCE:XRPUSDT', displayName: 'XRP/USDT' },
  { symbol: 'BINANCE:GTOTUSD', displayName: 'GTO/TUSD' },
  { symbol: 'BINANCE:ENJBUSD', displayName: 'ENJ/BUSD' },
  { symbol: 'BINANCE:ICPBUSD', displayName: 'ICP/BUSD' },
  { symbol: 'BINANCE:SXPBUSD', displayName: 'SXP/BUSD' },
  { symbol: 'BINANCE:MKRBUSD', displayName: 'MKR/BUSD' },
  { symbol: 'BINANCE:ZECUSDT', displayName: 'ZEC/USDT' },
  { symbol: 'BINANCE:DOGEBUSD', displayName: 'DOGE/BUSD' },
  { symbol: 'BINANCE:SKYBUSD', displayName: 'SKY/BUSD' },
  { symbol: 'BINANCE:RUNEBUSD', displayName: 'RUNE/BUSD' },
  { symbol: 'BINANCE:BCHBUSD', displayName: 'BCH/BUSD' },
  { symbol: 'BINANCE:FLMBUSD', displayName: 'FLM/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:RENBTCBUSD', displayName: 'RENBTC/BUSD' },
  { symbol: 'BINANCE:XMRUSDT', displayName: 'XMR/USDT' },
  { symbol: 'BINANCE:LTCBUSD', displayName: 'LTC/BUSD' },
  { symbol: 'BINANCE:GALABUSD', displayName: 'GALA/BUSD' },
  { symbol: 'BINANCE:BNBUSDT', displayName: 'BNB/USDT' },
  { symbol: 'BINANCE:WAXBUSD', displayName: 'WAX/BUSD' },
  { symbol: 'BINANCE:KSMBUSD', displayName: 'KSM/BUSD' },
  { symbol: 'BINANCE:VETBUSD', displayName: 'VET/BUSD' },
  { symbol: 'BINANCE:RVNBUSD', displayName: 'RVN/BUSD' },
  { symbol: 'BINANCE:YFIBUSD', displayName: 'YFI/BUSD' },
  { symbol: 'BINANCE:QTUMBUSD', displayName: 'QTUM/BUSD' },
  { symbol: 'BINANCE:SHRMBUSD', displayName: 'SHRM/BUSD' },
  { symbol: 'BINANCE:ETHUSDT', displayName: 'ETH/USDT' },
  { symbol: 'BINANCE:ATMBUSD', displayName: 'ATM/BUSD' },
  { symbol: 'BINANCE:XLMBUSD', displayName: 'XLM/BUSD' },
  { symbol: 'BINANCE:ZRXUSDT', displayName: 'ZRX/USDT' },
  { symbol: 'BINANCE:ERDBUSD', displayName: 'ERD/BUSD' },
  { symbol: 'BINANCE:ARABUSD', displayName: 'ARA/BUSD' },
  { symbol: 'BINANCE:USDCUSDT', displayName: 'USDC/USDT' },
  { symbol: 'BINANCE:XRPFDUSD', displayName: 'XRP/FDUSD' },
  { symbol: 'BINANCE:LINKBUSD', displayName: 'LINK/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:BLZBUSD', displayName: 'BLZ/BUSD' },
  { symbol: 'BINANCE:BCHBULLBUSD', displayName: 'BCHBULL/BUSD' },
  { symbol: 'BINANCE:BLZFDUSD', displayName: 'BLZ/FDUSD' },
  { symbol: 'BINANCE:DOTUSDT', displayName: 'DOT/USDT' },
  { symbol: 'BINANCE:ALICEBUSD', displayName: 'ALICE/BUSD' },
  { symbol: 'BINANCE:ATOMTUSD', displayName: 'ATOM/TUSD' },
  { symbol: 'BINANCE:ETHBULLBUSD', displayName: 'ETHBULL/BUSD' },
  { symbol: 'BINANCE:UNIBUSD', displayName: 'UNI/BUSD' },
  { symbol: 'BINANCE:TKOBUSD', displayName: 'TKO/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:BCHABCBUSD', displayName: 'BCHABC/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:ZRXBULLBUSD', displayName: 'ZRXBULL/BUSD' },
  { symbol: 'BINANCE:STORJFDUSD', displayName: 'STORJ/FDUSD' },
  { symbol: 'BINANCE:WINBUSD', displayName: 'WIN/BUSD' },
  { symbol: 'BINANCE:MBTCBUSD', displayName: 'MBTC/BUSD' },
  { symbol: 'BINANCE:STRAXBUSD', displayName: 'STRAX/BUSD' },
  { symbol: 'BINANCE:RENUSDT', displayName: 'REN/USDT' },
  { symbol: 'BINANCE:OCEANBUSD', displayName: 'OCEAN/BUSD' },
  { symbol: 'BINANCE:REEFBUSD', displayName: 'REEF/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:TRBBUSD', displayName: 'TRB/BUSD' },
  { symbol: 'BINANCE:BNBBEARBUSD', displayName: 'BNBBEAR/BUSD' },
  { symbol: 'BINANCE:INJBUSD', displayName: 'INJ/BUSD' },
  { symbol: 'BINANCE:MANABUSD', displayName: 'MANA/BUSD' },
  { symbol: 'BINANCE:STRKFDUSD', displayName: 'STRK/FDUSD' },
  { symbol: 'BINANCE:DOTBUSD', displayName: 'DOT/BUSD' },
  { symbol: 'BINANCE:AKROBUSD', displayName: 'AKRO/BUSD' },
  { symbol: 'BINANCE:SPARTABUSD', displayName: 'SPARTA/BUSD' },
  { symbol: 'BINANCE:ETHBULLBUSD', displayName: 'ETHBULL/BUSD' },
  { symbol: 'BINANCE:WRXBUSD', displayName: 'WRX/BUSD' },
  { symbol: 'BINANCE:YFIUSDT', displayName: 'YFI/USDT' },
  { symbol: 'BINANCE:BTGBUSD', displayName: 'BTG/BUSD' },
  { symbol: 'BINANCE:FTTUSDT', displayName: 'FTT/USDT' },
  { symbol: 'BINANCE:BCHABUSD', displayName: 'BCHAB/BUSD' },
  { symbol: 'BINANCE:ROSEUSDT', displayName: 'ROSE/USDT' },
  { symbol: 'BINANCE:MTLBUSD', displayName: 'MTL/BUSD' },
  { symbol: 'BINANCE:BTCBULLBUSD', displayName: 'BTCBULL/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:MKRBTCBUSD', displayName: 'MKRBTC/BUSD' },
  { symbol: 'BINANCE:TRXUSDT', displayName: 'TRX/USDT' },
  { symbol: 'BINANCE:ALICEBUSD', displayName: 'ALICE/BUSD' },
  { symbol: 'BINANCE:ROSEBUSD', displayName: 'ROSE/BUSD' },
  { symbol: 'BINANCE:ZRXBUSD', displayName: 'ZRX/BUSD' },
  { symbol: 'BINANCE:MDTBUSD', displayName: 'MDT/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:MDXUSDT', displayName: 'MDX/USDT' },
  { symbol: 'BINANCE:BANDUSDT', displayName: 'BAND/USDT' },
  { symbol: 'BINANCE:PNKBUSD', displayName: 'PNK/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:DMTBUSD', displayName: 'DMT/BUSD' },
  { symbol: 'BINANCE:XRPUSDT', displayName: 'XRP/USDT' },
  { symbol: 'BINANCE:GTOTUSD', displayName: 'GTO/TUSD' },
  { symbol: 'BINANCE:ENJBUSD', displayName: 'ENJ/BUSD' },
  { symbol: 'BINANCE:ICPBUSD', displayName: 'ICP/BUSD' },
  { symbol: 'BINANCE:SXPBUSD', displayName: 'SXP/BUSD' },
  { symbol: 'BINANCE:MKRBUSD', displayName: 'MKR/BUSD' },
  { symbol: 'BINANCE:ZECUSDT', displayName: 'ZEC/USDT' },
  { symbol: 'BINANCE:DOGEBUSD', displayName: 'DOGE/BUSD' },
  { symbol: 'BINANCE:SKYBUSD', displayName: 'SKY/BUSD' },
  { symbol: 'BINANCE:RUNEBUSD', displayName: 'RUNE/BUSD' },
  { symbol: 'BINANCE:BCHBUSD', displayName: 'BCH/BUSD' },
  { symbol: 'BINANCE:FLMBUSD', displayName: 'FLM/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:RENBTCBUSD', displayName: 'RENBTC/BUSD' },
  { symbol: 'BINANCE:XMRUSDT', displayName: 'XMR/USDT' },
  { symbol: 'BINANCE:LTCBUSD', displayName: 'LTC/BUSD' },
  { symbol: 'BINANCE:GALABUSD', displayName: 'GALA/BUSD' },
  { symbol: 'BINANCE:BNBUSDT', displayName: 'BNB/USDT' },
  { symbol: 'BINANCE:WAXBUSD', displayName: 'WAX/BUSD' },
  { symbol: 'BINANCE:KSMBUSD', displayName: 'KSM/BUSD' },
  { symbol: 'BINANCE:VETBUSD', displayName: 'VET/BUSD' },
  { symbol: 'BINANCE:RVNBUSD', displayName: 'RVN/BUSD' },
  { symbol: 'BINANCE:YFIBUSD', displayName: 'YFI/BUSD' },
  { symbol: 'BINANCE:QTUMBUSD', displayName: 'QTUM/BUSD' },
  { symbol: 'BINANCE:SHRMBUSD', displayName: 'SHRM/BUSD' },
  { symbol: 'BINANCE:ETHUSDT', displayName: 'ETH/USDT' },
  { symbol: 'BINANCE:ATMBUSD', displayName: 'ATM/BUSD' },
  { symbol: 'BINANCE:XLMBUSD', displayName: 'XLM/BUSD' },
  { symbol: 'BINANCE:ZRXUSDT', displayName: 'ZRX/USDT' },
  { symbol: 'BINANCE:ERDBUSD', displayName: 'ERD/BUSD' },
  { symbol: 'BINANCE:ARABUSD', displayName: 'ARA/BUSD' },
  { symbol: 'BINANCE:USDCUSDT', displayName: 'USDC/USDT' },
  { symbol: 'BINANCE:XRPFDUSD', displayName: 'XRP/FDUSD' },
  { symbol: 'BINANCE:LINKBUSD', displayName: 'LINK/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:BLZBUSD', displayName: 'BLZ/BUSD' },
  { symbol: 'BINANCE:BCHBULLBUSD', displayName: 'BCHBULL/BUSD' },
  { symbol: 'BINANCE:BLZFDUSD', displayName: 'BLZ/FDUSD' },
  { symbol: 'BINANCE:DOTUSDT', displayName: 'DOT/USDT' },
  { symbol: 'BINANCE:ALICEBUSD', displayName: 'ALICE/BUSD' },
  { symbol: 'BINANCE:ATOMTUSD', displayName: 'ATOM/TUSD' },
  { symbol: 'BINANCE:ETHBULLBUSD', displayName: 'ETHBULL/BUSD' },
  { symbol: 'BINANCE:UNIBUSD', displayName: 'UNI/BUSD' },
  { symbol: 'BINANCE:TKOBUSD', displayName: 'TKO/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:BCHABCBUSD', displayName: 'BCHABC/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:ZRXBULLBUSD', displayName: 'ZRXBULL/BUSD' },
  { symbol: 'BINANCE:STORJFDUSD', displayName: 'STORJ/FDUSD' },
  { symbol: 'BINANCE:WINBUSD', displayName: 'WIN/BUSD' },
  { symbol: 'BINANCE:MBTCBUSD', displayName: 'MBTC/BUSD' },
  { symbol: 'BINANCE:STRAXBUSD', displayName: 'STRAX/BUSD' },
  { symbol: 'BINANCE:RENUSDT', displayName: 'REN/USDT' },
  { symbol: 'BINANCE:OCEANBUSD', displayName: 'OCEAN/BUSD' },
  { symbol: 'BINANCE:REEFBUSD', displayName: 'REEF/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:TRBBUSD', displayName: 'TRB/BUSD' },
  { symbol: 'BINANCE:BNBBEARBUSD', displayName: 'BNBBEAR/BUSD' },
  { symbol: 'BINANCE:INJBUSD', displayName: 'INJ/BUSD' },
  { symbol: 'BINANCE:MANABUSD', displayName: 'MANA/BUSD' },
  { symbol: 'BINANCE:STRKFDUSD', displayName: 'STRK/FDUSD' },
  { symbol: 'BINANCE:DOTBUSD', displayName: 'DOT/BUSD' },
  { symbol: 'BINANCE:AKROBUSD', displayName: 'AKRO/BUSD' },
  { symbol: 'BINANCE:SPARTABUSD', displayName: 'SPARTA/BUSD' },
  { symbol: 'BINANCE:ETHBULLBUSD', displayName: 'ETHBULL/BUSD' },
  { symbol: 'BINANCE:WRXBUSD', displayName: 'WRX/BUSD' },
  { symbol: 'BINANCE:YFIUSDT', displayName: 'YFI/USDT' },
  { symbol: 'BINANCE:BTGBUSD', displayName: 'BTG/BUSD' },
  { symbol: 'BINANCE:FTTUSDT', displayName: 'FTT/USDT' },
  { symbol: 'BINANCE:BCHABUSD', displayName: 'BCHAB/BUSD' },
  { symbol: 'BINANCE:ROSEUSDT', displayName: 'ROSE/USDT' },
  { symbol: 'BINANCE:MTLBUSD', displayName: 'MTL/BUSD' },
  { symbol: 'BINANCE:BTCBULLBUSD', displayName: 'BTCBULL/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:MKRBTCBUSD', displayName: 'MKRBTC/BUSD' },
  { symbol: 'BINANCE:TRXUSDT', displayName: 'TRX/USDT' },
  { symbol: 'BINANCE:ALICEBUSD', displayName: 'ALICE/BUSD' },
  { symbol: 'BINANCE:ROSEBUSD', displayName: 'ROSE/BUSD' },
  { symbol: 'BINANCE:ZRXBUSD', displayName: 'ZRX/BUSD' },
  { symbol: 'BINANCE:MDTBUSD', displayName: 'MDT/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:MDXUSDT', displayName: 'MDX/USDT' },
  { symbol: 'BINANCE:BANDUSDT', displayName: 'BAND/USDT' },
  { symbol: 'BINANCE:PNKBUSD', displayName: 'PNK/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:DMTBUSD', displayName: 'DMT/BUSD' },
  { symbol: 'BINANCE:XRPUSDT', displayName: 'XRP/USDT' },
  { symbol: 'BINANCE:GTOTUSD', displayName: 'GTO/TUSD' },
  { symbol: 'BINANCE:ENJBUSD', displayName: 'ENJ/BUSD' },
  { symbol: 'BINANCE:ICPBUSD', displayName: 'ICP/BUSD' },
  { symbol: 'BINANCE:SXPBUSD', displayName: 'SXP/BUSD' },
  { symbol: 'BINANCE:MKRBUSD', displayName: 'MKR/BUSD' },
  { symbol: 'BINANCE:ZECUSDT', displayName: 'ZEC/USDT' },
  { symbol: 'BINANCE:DOGEBUSD', displayName: 'DOGE/BUSD' },
  { symbol: 'BINANCE:SKYBUSD', displayName: 'SKY/BUSD' },
  { symbol: 'BINANCE:RUNEBUSD', displayName: 'RUNE/BUSD' },
  { symbol: 'BINANCE:BCHBUSD', displayName: 'BCH/BUSD' },
  { symbol: 'BINANCE:FLMBUSD', displayName: 'FLM/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:RENBTCBUSD', displayName: 'RENBTC/BUSD' },
  { symbol: 'BINANCE:XMRUSDT', displayName: 'XMR/USDT' },
  { symbol: 'BINANCE:LTCBUSD', displayName: 'LTC/BUSD' },
  { symbol: 'BINANCE:GALABUSD', displayName: 'GALA/BUSD' },
  { symbol: 'BINANCE:BNBUSDT', displayName: 'BNB/USDT' },
  { symbol: 'BINANCE:WAXBUSD', displayName: 'WAX/BUSD' },
  { symbol: 'BINANCE:KSMBUSD', displayName: 'KSM/BUSD' },
  { symbol: 'BINANCE:VETBUSD', displayName: 'VET/BUSD' },
  { symbol: 'BINANCE:RVNBUSD', displayName: 'RVN/BUSD' },
  { symbol: 'BINANCE:YFIBUSD', displayName: 'YFI/BUSD' },
  { symbol: 'BINANCE:QTUMBUSD', displayName: 'QTUM/BUSD' },
  { symbol: 'BINANCE:SHRMBUSD', displayName: 'SHRM/BUSD' },
  { symbol: 'BINANCE:ETHUSDT', displayName: 'ETH/USDT' },
  { symbol: 'BINANCE:ATMBUSD', displayName: 'ATM/BUSD' },
  { symbol: 'BINANCE:XLMBUSD', displayName: 'XLM/BUSD' },
  { symbol: 'BINANCE:ZRXUSDT', displayName: 'ZRX/USDT' },
  { symbol: 'BINANCE:ERDBUSD', displayName: 'ERD/BUSD' },
  { symbol: 'BINANCE:ARABUSD', displayName: 'ARA/BUSD' },
  { symbol: 'BINANCE:USDCUSDT', displayName: 'USDC/USDT' },
  { symbol: 'BINANCE:XRPFDUSD', displayName: 'XRP/FDUSD' },
  { symbol: 'BINANCE:LINKBUSD', displayName: 'LINK/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:BLZBUSD', displayName: 'BLZ/BUSD' },
  { symbol: 'BINANCE:BCHBULLBUSD', displayName: 'BCHBULL/BUSD' },
  { symbol: 'BINANCE:BLZFDUSD', displayName: 'BLZ/FDUSD' },
  { symbol: 'BINANCE:DOTUSDT', displayName: 'DOT/USDT' },
  { symbol: 'BINANCE:ALICEBUSD', displayName: 'ALICE/BUSD' },
  { symbol: 'BINANCE:ATOMTUSD', displayName: 'ATOM/TUSD' },
  { symbol: 'BINANCE:ETHBULLBUSD', displayName: 'ETHBULL/BUSD' },
  { symbol: 'BINANCE:UNIBUSD', displayName: 'UNI/BUSD' },
  { symbol: 'BINANCE:TKOBUSD', displayName: 'TKO/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:BCHABCBUSD', displayName: 'BCHABC/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:ZRXBULLBUSD', displayName: 'ZRXBULL/BUSD' },
  { symbol: 'BINANCE:STORJFDUSD', displayName: 'STORJ/FDUSD' },
  { symbol: 'BINANCE:WINBUSD', displayName: 'WIN/BUSD' },
  { symbol: 'BINANCE:MBTCBUSD', displayName: 'MBTC/BUSD' },
  { symbol: 'BINANCE:STRAXBUSD', displayName: 'STRAX/BUSD' },
  { symbol: 'BINANCE:RENUSDT', displayName: 'REN/USDT' },
  { symbol: 'BINANCE:OCEANBUSD', displayName: 'OCEAN/BUSD' },
  { symbol: 'BINANCE:REEFBUSD', displayName: 'REEF/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:TRBBUSD', displayName: 'TRB/BUSD' },
  { symbol: 'BINANCE:BNBBEARBUSD', displayName: 'BNBBEAR/BUSD' },
  { symbol: 'BINANCE:INJBUSD', displayName: 'INJ/BUSD' },
  { symbol: 'BINANCE:MANABUSD', displayName: 'MANA/BUSD' },
  { symbol: 'BINANCE:STRKFDUSD', displayName: 'STRK/FDUSD' },
  { symbol: 'BINANCE:DOTBUSD', displayName: 'DOT/BUSD' },
  { symbol: 'BINANCE:AKROBUSD', displayName: 'AKRO/BUSD' },
  { symbol: 'BINANCE:SPARTABUSD', displayName: 'SPARTA/BUSD' },
  { symbol: 'BINANCE:ETHBULLBUSD', displayName: 'ETHBULL/BUSD' },
  { symbol: 'BINANCE:WRXBUSD', displayName: 'WRX/BUSD' },
  { symbol: 'BINANCE:YFIUSDT', displayName: 'YFI/USDT' },
  { symbol: 'BINANCE:BTGBUSD', displayName: 'BTG/BUSD' },
  { symbol: 'BINANCE:FTTUSDT', displayName: 'FTT/USDT' },
  { symbol: 'BINANCE:BCHABUSD', displayName: 'BCHAB/BUSD' },
  { symbol: 'BINANCE:ROSEUSDT', displayName: 'ROSE/USDT' },
  { symbol: 'BINANCE:MTLBUSD', displayName: 'MTL/BUSD' },
  { symbol: 'BINANCE:BTCBULLBUSD', displayName: 'BTCBULL/BUSD' },
  { symbol: 'BINANCE:XRPBULLBUSD', displayName: 'XRPBULL/BUSD' },
  { symbol: 'BINANCE:MKRBTCBUSD', displayName: 'MKRBTC/BUSD' },
  { symbol: 'BINANCE:TRXUSDT', displayName: 'TRX/USDT' },
  { symbol: 'BINANCE:ALICEBUSD', displayName: 'ALICE/BUSD' },
  { symbol: 'BINANCE:ROSEBUSD', displayName: 'ROSE/BUSD' },
  { symbol: 'BINANCE:ZRXBUSD', displayName: 'ZRX/BUSD' },
  { symbol: 'BINANCE:MDTBUSD', displayName: 'MDT/BUSD' },
  { symbol: 'BINANCE:VIDTBUSD', displayName: 'VIDT/BUSD' },
  { symbol: 'BINANCE:MDXUSDT', displayName: 'MDX/USDT' },
  { symbol: 'BINANCE:BANDUSDT', displayName: 'BAND/USDT' },
  { symbol: 'BINANCE:PNKBUSD', displayName: 'PNK/BUSD' },
  { symbol: 'BINANCE:THETABUSD', displayName: 'THETA/BUSD' },
  { symbol: 'BINANCE:DMTBUSD', displayName: 'DMT/BUSD' },
  { symbol: 'BINANCE:XRPUSDT', displayName: 'XRP/USDT' },
  { symbol: 'BINANCE:GTOTUSD', displayName: 'GTO/TUSD' },
  { symbol: 'BINANCE:ENJBUSD', displayName: 'ENJ/BUSD' },
  { symbol: 'BINANCE:ICPBUSD', displayName: 'ICP/BUSD' },
  { symbol: 'BINANCE:SXPBUSD', displayName: 'SXP/BUSD' },
  { symbol: 'BINANCE:MKRBUSD', displayName: 'MKR/BUSD' },
  { symbol: 'BINANCE:ZECUSDT', displayName: 'ZEC/USDT' },
  { symbol: 'BINANCE:DOGEBUSD', displayName: 'DOGE/BUSD' },
  { symbol: 'BINANCE:SKYBUSD', displayName: 'SKY/BUSD' },
  { symbol: 'BINANCE:RUNEBUSD', displayName: 'RUNE/BUSD' },
  { symbol: 'BINANCE:BCHBUSD', displayName: 'BCH/BUSD' },
  { symbol: 'BINANCE:FLMBUSD', displayName: 'FLM/BUSD' },
  { symbol: 'BINANCE:ADAUSDT', displayName: 'ADA/USDT' },
  { symbol: 'BINANCE:RENBTCBUSD', displayName: 'RENBTC/BUSD' },
  { symbol: 'BINANCE:XMRUSDT', displayName: 'XMR/USDT' },
  { symbol: 'BINANCE:LTCBUSD', displayName: 'LTC/BUSD' },
  { symbol: 'BINANCE:GALABUSD', displayName: 'GALA/BUSD' },
  { symbol: 'BINANCE:BNBUSDT', displayName: 'BNB/USDT' },
  { symbol: 'BINANCE:WAXBUSD', displayName: 'WAX/BUSD' },
  { symbol: 'BINANCE:KSMBUSD', displayName: 'KSM/BUSD' },
  { symbol: 'BINANCE:VETBUSD', displayName: 'VET/BUSD' },
  { symbol: 'BINANCE:RVNBUSD', displayName: 'RVN/BUSD' },
  { symbol: 'BINANCE:YFIBUSD', displayName: 'YFI/BUSD' },
  { symbol: 'BINANCE:QTUMBUSD', displayName: 'QTUM/BUSD' },
  { symbol: 'BINANCE:SHRMBUSD', displayName: 'SHRM/BUSD' },
  { symbol: 'BINANCE:ETHUSDT', displayName: 'ETH/USDT' },
  { symbol: 'BINANCE:ATMBUSD', displayName: 'ATM/BUSD' }
]
